spring:
  application:
    name: population-batch
  datasource:
    url: ${NKE_DMO_DATASOURCE_URL:jdbc:h2:file:./data/db/nke-demo-db;MODE=PostgreSQL}
    username: ${NKE_DMO_DATASOURCE_USER:sa}
    password: ${NKE_DMO_DATASOURCE_PASSWORD:}
    type:
    driver-class-name: ${NKE_DMO_DATASOURCE_DRIVER:org.h2.Driver}
    hikari:
      minimumIdle: ${NKE_DMO_CONNECTIONPOOL_SIZE_MIN:2}
      maximumPoolSize: ${NKE_DMO_CONNECTIONPOOL_SIZE_MAX:6}
      idleTimeout: ${NKE_DMO_CONNECTIONPOOL_IDLE_TIMEOUT:30000}
      maxLifetime: ${NKE_DMO_CONNECTIONPOOL_MAX_LIFE_TIME:2000000}
      connectionTimeout: ${NKE_DMO_CONNECTION_TIMEOUT:30000}
  batch:
    jdbc:
      initialize-schema: always

populationBatch:
  h2Enabled: true
  ghsl:
    # possible resolutions are:
    # 4326_30ss  - WGS84 30arcsec
    # 4326_3ss   - WGS84 3arcsec
    # 54009_100  - Mollweide 100m
    # 54009_1000 - Mollweide 1000m
    skipDownload: true
    skipProcessing: true
    resolution: 4326_30ss
    overwriteSourceZipFiles: false
    maxRow: 18
    maxColumn: 36
    resultFolder: "./data/res/population/ghsl/${populationBatch.ghsl.resolution}/"